### ISSUE TITLE
1.4.1 update

### ISSUE THREAD

**Issue by wizzy1066** [ddewar/FS22_UniversalAutoloadModhubAddon#3]
the 1.4.1 update has broken this mod will not load game pass 60%

**Comment by FrmrJon** [comment]
I am also having this issue.

**Comment by ddewar** [comment]
Hey there, are you using the release pushed yesterday? I cleaned up the issue. If it is an issue with the 0.0.2-beta release, then please send me a log if you have it!

https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v0.0.2-beta

**Comment by wizzy1066** [comment]
![image](https://user-images.githubusercontent.com/95526831/165224769-3ace3145-1891-4da3-8553-f43e27129d39.png)


there you go

**Comment by ddewar** [comment]
> ![image](https://user-images.githubusercontent.com/95526831/165224769-3ace3145-1891-4da3-8553-f43e27129d39.png)
> 
> there you go

Yeah, I believe I fixed this with the latest release/tag. Try the version from the link above?

**Comment by wizzy1066** [comment]
that the vesion i just tryed

**Comment by loki79uk** [comment]
Try replacing that line with:
`FS22_UniversalAutoload.UniversalAutoload.ImportVehicleConfigurations(vehicleSettingsFile)`

Of course, there will still an issue if someone renames the UniversalAutoload zip file, but that should work for now.  I'll think about a safer way to permanently solve this..

**Comment by loki79uk** [comment]
> so you mean rename the zip file to that line ?

No, just replace line 10 in the lua file.  i.e. add the namespace onto the begining.  It is only a temporary fix to get it working for now before using something permanent (that will require a change to UAL).

**Comment by wizzy1066** [comment]
work great now ty kind sir
